# Generated by Django 4.2.2 on 2023-06-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cc', 'CC'), ('ce', 'CE'), ('ti', 'TI'), ('nn', 'NN')], max_length=2)),
                ('document', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('m', 'M'), ('f', 'F'), ('n', 'N')], max_length=1, null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cc', 'CC'), ('ce', 'CE'), ('ti', 'TI'), ('nn', 'NN')], max_length=2)),
                ('document', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('m', 'M'), ('f', 'F'), ('n', 'N')], max_length=1, null=True)),
                ('career', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('hours', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('fk_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('fk_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.student')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.FloatField(null=True)),
                ('fk_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('fk_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.student')),
                ('fk_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='fk_student',
            field=models.ManyToManyField(through='course.Tuition', to='course.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='fk_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.teacher'),
        ),
    ]
