# Generated by Django 4.2.2 on 2023-06-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_student_city_student_country_student_is_virtual_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tuition',
            unique_together={('fk_student', 'fk_course')},
        ),
    ]
